#!/usr/bin/env bash
set -euo pipefail

# sign-publish-tx.sh - Sign and submit a transaction generated by the offchain CLI.
# Usage: NETWORK=preprod scripts/sign-publish-tx.sh [path-to-unsigned-tx]

# shellcheck source=scripts/_lib.sh
source "$(dirname "$0")/_lib.sh"

# ── Network flag ─────────────────────────────────────────────────────────────

case "${NETWORK:-preprod}" in
    mainnet) NETWORK_FLAG=(--mainnet) ;;
    preview) NETWORK_FLAG=(--testnet-magic 2) ;;
    *)       NETWORK_FLAG=(--testnet-magic 1) ;;
esac

# ── Resolve tx file path ─────────────────────────────────────────────────────

TX_UNSIGNED="${1:-${REPO_ROOT}/contracts/treasury-contracts/offchain/tx.unsigned}"

if [[ ! -f "$TX_UNSIGNED" ]]; then
    echo "Error: Transaction file not found: ${TX_UNSIGNED}" >&2
    echo "Usage: scripts/sign-publish-tx.sh [path-to-unsigned-tx]" >&2
    exit 1
fi

echo "=== Sign Transaction ==="
echo ""
echo "Network:  ${NETWORK_FLAG[*]}"
echo "Tx file:  ${TX_UNSIGNED}"
echo ""

# ── Resolve signing key ──────────────────────────────────────────────────────

if [[ -n "${PAYMENT_HW_SIGNING_FILE:-}" ]]; then
    HW_PATH="${PAYMENT_HW_SIGNING_FILE}"
    if [[ "$HW_PATH" != /* ]]; then
        HW_PATH="${REPO_ROOT}/${HW_PATH}"
    fi
    if [[ ! -f "$HW_PATH" ]]; then
        echo "Error: Hardware signing file not found: ${HW_PATH}" >&2
        exit 1
    fi

    TX_WITNESS="${TX_UNSIGNED%.unsigned}.witness"
    TX_SIGNED="${TX_UNSIGNED%.unsigned}.signed"

    echo "Signing with hardware wallet: ${HW_PATH}"

    echo "Transforming transaction to canonical CBOR..."
    cardano-hw-cli transaction transform \
        --tx-file "$TX_UNSIGNED" \
        --out-file "$TX_UNSIGNED"

    cardano-hw-cli transaction witness \
        "${NETWORK_FLAG[@]}" \
        --tx-file "$TX_UNSIGNED" \
        --hw-signing-file "$HW_PATH" \
        --out-file "$TX_WITNESS"

    echo "Witness created: ${TX_WITNESS}"

    cardano-cli conway transaction assemble \
        --tx-body-file "$TX_UNSIGNED" \
        --witness-file "$TX_WITNESS" \
        --out-file "$TX_SIGNED"

    rm -f "$TX_WITNESS"

elif [[ -n "${PAYMENT_SKEY:-}" ]]; then
    SKEY_PATH="${PAYMENT_SKEY}"
    if [[ "$SKEY_PATH" != /* ]]; then
        SKEY_PATH="${REPO_ROOT}/${SKEY_PATH}"
    fi
    if [[ ! -f "$SKEY_PATH" ]]; then
        echo "Error: Signing key not found: ${SKEY_PATH}" >&2
        exit 1
    fi

    TX_SIGNED="${TX_UNSIGNED%.unsigned}.signed"

    echo "Signing with key file: ${SKEY_PATH}"

    cardano-cli conway transaction sign \
        "${NETWORK_FLAG[@]}" \
        --tx-body-file "$TX_UNSIGNED" \
        --signing-key-file "$SKEY_PATH" \
        --out-file "$TX_SIGNED"
else
    echo "Error: Neither PAYMENT_HW_SIGNING_FILE nor PAYMENT_SKEY is set." >&2
    exit 1
fi

echo "Signed transaction: ${TX_SIGNED}"

# ── Submit ───────────────────────────────────────────────────────────────────

echo ""
echo "Submitting transaction..."

cardano-cli conway transaction submit \
    "${NETWORK_FLAG[@]}" \
    --tx-file "$TX_SIGNED"

TX_HASH=$(cardano-cli conway transaction txid --tx-file "$TX_SIGNED")

echo ""
echo "Transaction submitted successfully."
echo "Transaction hash: ${TX_HASH}"
